# =========================================================================
# Local Configuration for HA-Watchdog
# =========================================================================

substitutions:
  devicename: "ha-watchdog"
  fdly_name: "HA Watchdog"
  # Calibration values (Adjust based on your specific plug)
  current_res: "0.00280"
  voltage_div: "706"
  # Time settings
  watchdog_on_time: "300s"
  watchdog_off_time: "60s"

packages:
  # Pulling the logic from your GitHub repository
  remote_logic:
    url: https://github.com/SCiunczyk/esphome-wdt-socket
    refresh: 1d
    files: [nous-a1t-wdt.yaml]

esphome:
  name: ${devicename}
  friendly_name: ${fdly_name}
  comment: "Nous Smart Wifi Socket A1T (HA Odroid N2+ Watchdog)"
  name_add_mac_suffix: false

# Restored original multi-network Wi-Fi configuration
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      priority: 1
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password2
      priority: 2
    - ssid: !secret wifi_ssid3
      password: !secret wifi_password3
      priority: 3
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename}-ap"

captive_portal:

api:
  encryption:
    key: !secret ha_api_key

ota:
  - platform: esphome
    password: !secret ota_password

web_server:
  port: 80

logger:
  level: INFO
